# docker/mysql/Dockerfile

FROM mysql:5.7

# Definir variáveis de ambiente para o MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=laravel
ENV MYSQL_USER=laravel
ENV MYSQL_PASSWORD=secret

EXPOSE 3306
